version: '2'
services:
  portainer:
    image: registry.cn-hangzhou.aliyuncs.com/slzcc/portainer:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    hostname: hadoop-slave1
